//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMedico.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendamentoConsultas
    {
        public int idAgendamento { get; set; }
        public int idPaciente { get; set; }
        public int idMedico { get; set; }
        public int idEspecialidade { get; set; }
        public System.DateTime DataConsulta { get; set; }
    
        public virtual CadEspecialidades CadEspecialidades { get; set; }
        public virtual CadMedicos CadMedicos { get; set; }
        public virtual CadPacientes CadPacientes { get; set; }
    }
}
