//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMedico.Controller
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDSistemaConsultorioEntities : DbContext
    {
        public BDSistemaConsultorioEntities()
            : base("name=BDSistemaConsultorioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgendamentoConsultas> AgendamentoConsultas { get; set; }
        public virtual DbSet<CadEspecialidades> CadEspecialidades { get; set; }
        public virtual DbSet<CadMedicos> CadMedicos { get; set; }
        public virtual DbSet<CadPacientes> CadPacientes { get; set; }
        public virtual DbSet<ManutUsers> ManutUsers { get; set; }
    }
}
