//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMedico.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadMedicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadMedicos()
        {
            this.AgendamentoConsultas = new HashSet<AgendamentoConsultas>();
        }
    
        public int idMedico { get; set; }
        public string Medico { get; set; }
        public string CRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendamentoConsultas> AgendamentoConsultas { get; set; }
    }
}
